name: 🧪 Validate Metadata
run-name: 🧪 Validate (${{ github.event_name }})

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Validate Metadata
    runs-on: ubuntu-22.04
    container:
      image: nycplanning/dev:latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: NYCPlanning/product-metadata
          path: product-metadata
      - uses: actions/checkout@v4
        with:
          repository: NYCPlanning/data-engineering
          path: data-engineering
      - name: Validate All Files
        run: cd data-engineering; python -m dcpy lifecycle scripts product_metadata validate_repo ../product-metadata
        env:
          RECIPES_BUCKET: edm-recipes
          PUBLISHING_BUCKET: edm-publishing
